### ISSUE TITLE
Guía de Canal Extremadura SAT

### ISSUE THREAD

**Issue by Colaborador30** [dracohe/CARLOS#1]
Hola.

La guía de Canal Etremadura http://www.movistarplus.es/canal/canal-extremadura?id=EXTRE, no es la de Canal Extremadura SAT http://www.movistarplus.es/canal/canal-extremadura-sat?id=EXTREM (que es la emisión que se puede ver por internet).

Tienes que usar el id "EXTREM" en lugar de "EXTRE".

Gracias por tu trabajo.

**Comment by dracohe** [comment]
Muchas gracias por tu aporte, ya lo he cambiado para la próxima captura, un saludo
