### ISSUE TITLE
Más canales

### ISSUE THREAD

**Issue by Berto9050** [dracohe/CARLOS#2]
Hola. Soy nuevo aquí y no sabía cómo escribirte directamente, así que abrí un Issue.

Era para pasarte estos canales por si te parecía interesante agregarlos a tu lista.

channel update="i" site="dw.com" site_id="3_6309/28" xmltv_id="DW (EspaÃ±ol)">DW en EspaÃ±ol</channel
channel update="i" site="movistarplus.es" site_id="RTESP" xmltv_id="RT EspaÃ±ol">RT en EspaÃ±ol</channel
channel update="i" site="movistarplus.es" site_id="CCTV-E" xmltv_id="CCTV EspaÃ±ol">CGTN en EspaÃ±ol</channel

Un saludo.

**Comment by dracohe** [comment]
Hola, esos uno lo tenia añadido, los otros dos no, te lo añado para mañana, pero tiene que ser con esta otra url

https://raw.githubusercontent.com/dracohe/INTERNACIONALES/master/guide.xml.gz

si usas mi epg en enigma2, mira este manual y activas las dos , carlos y carlos inter

https://telegra.ph/EPG-ENIGMA2-PARA-5-D%C3%8DAS-03-12

**Comment by Berto9050** [comment]
No me había fijado que sólo salían los nombres de los canales en el mensaje que te envié. Le he quitado el "<" y el ">" del principio y final de cada línea para que puedas ver de dónde sacar la info. La idea era facilitar el trabajo.

Estuve mirando esa otra URL y ya tiene RT, no la había visto. Y ya que es de canales internacionales te dejo este por si también te interesa:
channel update="i" site="gatotv.com" site_id="ntn24_nuestra_tele_noticias" xmltv_id="NTN24 (Nuestra Tele Noticias 24 Horas)">NTN24</channel

Y no uso Enigma2 sino ProgTV que carga una lista y pide url para la guía.  Me permite poner dos url para la guía así que las usaré como complementarias.

Muchas gracias.
