### ISSUE TITLE
Más canales

### ISSUE THREAD

**Issue by Berto9050** [dracohe/CARLOS#4]
Hola.

Crees que podrías agregar Canal Extremadura y Aragón TV para los que usan la guía con programas como tvheadend para ver la TDT? Si fuese posible también en la guía COLOR.
http://www.movistarplus.es/canal/canal-extremadura?id=EXTRE
http://www.movistarplus.es/canal/aragon-tv?id=ARAGTV

Gracias por tu trabajo.

**Comment by dracohe** [comment]
Esos canales ya están incluidos en la epg

**Comment by Berto9050** [comment]
> Esos canales ya están incluidos en la epg

Los que están incluídos son:
http://www.movistarplus.es/canal/canal-extremadura-sat?id=EXTREM (es diferente al id EXTRE)
http://www.movistarplus.es/canal/aragon-tv-int?id=ARAGON (es diferente al id ARAGTV)

La idea era tener ambas guías para cada canal, tanto la de la emisión por internet como la de la emisión por TDT.

**Comment by dracohe** [comment]
Ya los tienes añadidos compruébalo, un saludo

**Comment by Berto9050** [comment]
Comprobado. Están en la CARLOS y en la COLOR.
Lo único es que tienes intercambiados los nombres de Aragón (es decir, el INT es el de TDT y viceversa). Sólo tendrías que cambiarles los nombres, porque las guías y los logos ya estarían bien.

Muchas gracias.
