### ISSUE TITLE
Petición mejora para Android TV

### ISSUE THREAD

**Issue by atvuser20** [dracohe/CARLOS#6]
Hola,

Esta guía es excelente, y la estoy usando desde hace un tiempo. Mi dispositivo es Android TV, así que utilizo el Live Channels para visualizarla. Y en mi caso la mejor versión es la SMARTIPTV, así que utilizo este enlace: https://github.com/dracohe/SMARTIPTV/blob/master/guide.xml.gz?raw=true

Pero tengo un pequeño problema, que tal vez podáis solucionar. Resulta que en Android TV, la guía no puede imprimir todo lo que se quiera, así que recorta los textos. Pero como la guía tiene varias líneas en el campo de descripción pues no queda muy bien.

Voy a explicarlo con un ejemplo:
```
  <programme start="20210301220000 +0100" stop="20210302000000 +0100" channel="La 2 HD">
    <title lang="es">Centauros del desierto</title>
    <desc lang="es">★★★☆☆  Cine, Oeste. (+12) 1956. EE.UU Dir: John Ford. Int: John Wayne, Jeffrey Hunter, Vera Miles, Ward Bond, Natalie Wood, John Qualen, Dorothy Jordan, Olive Carey, Peter Mamakos. 
Argumento: Tres años después de la finalización de la guerra de Secesión, Ethan Edwards (John Wayne), ex oficial que ha luchado en el ejército confederado, solitario, vengativo y marcado por su extremo odio hacia los indios, vuelve a su querido hogar formado por su hermano Aaron (Walter Coy), su cuñada Martha (Dorothy Jordan), sus dos sobrinas Lucy (Pippa Scott) y Debbie (Lana Wood) y un muchacho medio mestizo llamado Martin (Jeffrey Hunter). Lucy está prometida a un joven muchacho llamado Brad Jorgensen (Harry Carey Jr.), cuya familia vive cerca, mientras que Laurie (Vera Miles), la hermana de Brad, está enamorada de Martin. Una incursión comanche acaba con todos los miembros de la familia, llevándose los indios como botín a sus dos sobrinas. Ethan se lanza en su búsqueda; una búsqueda sangrienta e incansable, que durará diez años. Una de las muchachas, Lucy, aparecerá muerta pronto, pero cuando Ethan consigue localizar a su otra sobrina en la tribu de gran jefe Cicatriz (Henry Brandon), Debbie (Nathalie Wood) ya es toda una mujer comanche, que se niega a abandonar su nueva raza. Un western insólito dentro de la filmografía del Oeste y una de las grandes obras maestras de John Ford, donde reivindica el individualismo frente a la estructura coral que solían ofrecer sus anteriores películas. Igualmente este bello, emotivo y angustiado filme está impregnado de un pesimismo que contradice el sentido del humor, la nostalgia y el calor humano que presiden todos sus westerns. Así, aquella nostalgia y el humanismo que habían caracterizado a los westerns de Ford realizados durante la década de los cuarenta se transformaron en angustia y desesperación en los cincuenta con esta obra claramente influenciada por la variante psicológica del género aparecida por aquellos años. La historia de un hombre que, tras luchar en la Guerra de Secesión, regresa a su casa descubriendo que los indios han acabado con toda su familia llevándose secuestradas a las dos niñas pequeñas. Este hombre se pasará más de una década buscándolas. </desc>
    <category lang="es">Cine</category>
    <category lang="es">Oeste</category>
    <icon src="https://www.movistarplus.es/recorte/n/caratula4/MLA2P65655" />
    <country lang="es">EE.UU</country>
    <star-rating system="ES">
      <value>★★★☆☆</value>
    </star-rating>
    <review type="text">Ratings: 12.</review>
  </programme>
```
Si miráis bien el campo `desc` se puede ver que la PRIMERA línea es bastante larga. Y lo que hace Android entonces es continuar en la segunda línea, y luego viene el final de línea; por lo que ya no se puede ver nada del argumento (solo deja espacio para dos líneas después del título-subtítulo). Así que si la PRIMERA línea se cortase, entonces se podría leer mejor. Un ejemplo de cómo quedaría el campo anterior con lo que digo:
```
    <desc lang="es">★★★☆☆  Cine, Oeste. (+12) 1956. EE.UU Dir: John Ford. Int: John Wayne... 
Argumento: Tres años después de la finalización de la guerra de Secesión, Ethan Edwards (John Wayne), ex oficial que ha luchado en el ejército confederado, solitario, vengativo y marcado por su extremo odio hacia los indios, vuelve a su querido hogar formado por su hermano Aaron (Walter Coy), su cuñada Martha (Dorothy Jordan), sus dos sobrinas Lucy (Pippa Scott) y Debbie (Lana Wood) y un muchacho medio mestizo llamado Martin (Jeffrey Hunter). Lucy está prometida a un joven muchacho llamado Brad Jorgensen (Harry Carey Jr.), cuya familia vive cerca, mientras que Laurie (Vera Miles), la hermana de Brad, está enamorada de Martin. Una incursión comanche acaba con todos los miembros de la familia, llevándose los indios como botín a sus dos sobrinas. Ethan se lanza en su búsqueda; una búsqueda sangrienta e incansable, que durará diez años. Una de las muchachas, Lucy, aparecerá muerta pronto, pero cuando Ethan consigue localizar a su otra sobrina en la tribu de gran jefe Cicatriz (Henry Brandon), Debbie (Nathalie Wood) ya es toda una mujer comanche, que se niega a abandonar su nueva raza. Un western insólito dentro de la filmografía del Oeste y una de las grandes obras maestras de John Ford, donde reivindica el individualismo frente a la estructura coral que solían ofrecer sus anteriores películas. Igualmente este bello, emotivo y angustiado filme está impregnado de un pesimismo que contradice el sentido del humor, la nostalgia y el calor humano que presiden todos sus westerns. Así, aquella nostalgia y el humanismo que habían caracterizado a los westerns de Ford realizados durante la década de los cuarenta se transformaron en angustia y desesperación en los cincuenta con esta obra claramente influenciada por la variante psicológica del género aparecida por aquellos años. La historia de un hombre que, tras luchar en la Guerra de Secesión, regresa a su casa descubriendo que los indios han acabado con toda su familia llevándose secuestradas a las dos niñas pequeñas. Este hombre se pasará más de una década buscándolas. </desc>
```
Como podréis ver ahora la primera línea es más corta y lo demás no cambia. Así se podría ver mucho mejor en Android TV.

¿Qué estoy pidiendo entonces? A ver si podéis publicar una versión que solo haga es cambio: que si la primera línea del campo `desc` es más larga de 80 caracteres, que entonces corte en el 81 hasta el final de la línea, y añada `...\r\n` al final de esa; para luego continuar con el resto (no hay que tocar/cambiar ninguna otra cosa). Tal vez eso se podría hacer con un `sed` o de alguna otra forma, y publicar el enlace junto al SMARTIPTV, pero con otro nombre (tal vez ANDROIDTV).

¿Qué os parece esta idea? ¿Es posible? ¿Es fácil?
Probablemente hasta ahora nadie haya visto esto, pero es un palo en Android TV no poder ver bien el argumento por culpa de líneas demasiado largas, por ejemplo, cuando se añaden todos los actores en la primera línea.
Espero que podáis hacerlo algo.
Gracias.

**Comment by dracohe** [comment]
Deberías usar otra aplicación, todas las demás se visualiza perfectamente, eso es fallo de live channels, puedes probar otras como kodi,tivimate, iptvextre... cualquiera de ellas te va a funcionar mejor.

**Comment by regdisc27** [comment]
Pues yo tengo una tele con AndroidTV y prefiero utilizar el reproductor stock que no el tivimate. Y no hablemos ya de los smartiptv, iptvextreme, iptv...lo que sea, son muy malos. Y de KODI mejor ni hablemos, porque hace falta tener un servidor en marcha. Con la propia tele y alguna app como tvirl o pvr live es 100veces mejor.

Y lo que dice el amigo es cierto: no se puede leer todo. La culpa es de Google, sí, pero una lista con la línea cortada podría ayudar. Yo por lo menos si la publicáis la probaría. Imagino que no será tan difícil de hacer, ¿verdad?

**Comment by dracohe** [comment]
No seguro que no es difícil pero es mejor que uses la de la jungle si, esto es voluntario y gratis , atiendo sugerencias pero no exigencias, no voy a hacer una epg diferente para cada aplicación porque no le guste las demás, para mi si son mejores.
